### ISSUE TITLE
docs.rs documentation failed

### ISSUE THREAD

**Issue by CAD97** [salsa-rs/salsa#136]
https://docs.rs/crate/salsa/0.10.0-alpha5/builds/139182

It looks to be a docs.rs problem, so I [reported it there](https://github.com/rust-lang/docs.rs/issues/23#issuecomment-457780826), but I thought it would be good to mention it here as well.

**Comment by KenSuenobu** [comment]
Seconded.  Regard: https://docs.rs/crate/rust-pushrod/0.1.5/builds/139474

**Comment by CAD97** [comment]
[The documentation has been fixed.](https://docs.rs/salsa/0.10.0/salsa/)
