### ISSUE TITLE
Create a "salsa book" and publish automatically

### ISSUE THREAD

**Issue by nikomatsakis** [salsa-rs/salsa#15]
We have the [Hello World example](https://github.com/salsa-rs/salsa/tree/master/examples/hello_world), which serves as a basic tutorial, but it does not show off some of salsa's other features, like `set_constant` or parallel snapshots.

I think the first step here is actually adding a `mdbook` setup to the repository and configuring travis to publish it (along with the "master" rustdocs, I imagine).

**Comment by CAD97** [comment]
I'm interested in picking up salsa for my own work, and in putting my learning effort into creating (or at least sketching) a tutorial.

What kind of question to solve would be a good fit for a tutorial? How much support code should it start with?

**Comment by nikomatsakis** [comment]
Good question @CAD97 -- there is already the [Hello World example](https://github.com/salsa-rs/salsa/tree/master/examples/hello_world), which serves as a basic tutorial. It does not show off some of salsa's other features, like `set_constant` or parallel snapshots.

I think the first step here is actually adding a `mdbook` setup to the repository and configuring travis to publish it (along with the "master" rustdocs, I imagine).

**Comment by nikomatsakis** [comment]
I'm going to rename the issue as such.

**Comment by nikomatsakis** [comment]
So we [have a book now](https://salsa-rs.github.io/salsa/) but we have to actually add contents. =) I'm going to close this issue and open a new one about *populating* the book.
