### ISSUE TITLE
Factor out read notification?

### ISSUE THREAD

**Issue by nikomatsakis** [salsa-rs/salsa#16]
Right now, each storage winds up notifying the active task of a read. This seems repetitive. I'd like to factor it out, but I'm not 100% sure where to factor it out *to*. Moving the logic into the `QueryTable::get` method is one possibility, but somehow doesn't "feel right" to me. I expect that code to kind of be a "convenience wrapper" around the `QueryStorageOps` trait. Perhaps implement `QueryStorageOps::try_fetch` in terms of some inner method, which is the only actually implemented? (And have `try_fetch` return a `StampedValue`...)

**Comment by matklad** [comment]
Should be closed I guess. This is basically https://github.com/salsa-rs/salsa/blob/12deacbbb568546be32129a8b414bb667285471b/src/runtime.rs#L137, right?

**Comment by nikomatsakis** [comment]
Yeah I think this is clean enough now.
