### ISSUE TITLE
cleanup public exports and module structure

### ISSUE THREAD

**Issue by nikomatsakis** [salsa-rs/salsa#17]
We have a fair amount of stuff exported from the root that probably belongs in a "plumbing" module of some kind, since people shouldn't have to interact with it directly.

This includes basically everything but (a) the macros, (b) the `QueryContext` trait, and (c) the `DefaultKey` trait (assuming we keep that).

OTOH we might want to `pub use` the `Runtime` so that people can write `salsa::Runtime` and not `salsa::runtime::Runtime`.

**Comment by matklad** [comment]
What module structure do we envision?

I suggest creating a literal `pub mod plumbing`, with a doc comments along the lines of

> Items in this module are public for implementation reasons (they are used by macros), you should not use them directly and they are excluded from the semver compatibility guarantees.

Then, we'll dump most of the stuff from `lib.rs` to the `plumbing`. I think that'll give use the public API we want.

Internally, a small paper cut would be that we'll need to import things either from `crate::`, or from `crate::plumbing`, but I don't think that is really important.

**Comment by nikomatsakis** [comment]
That is roughly what I had in mind, yes. I'm not sure which things should remain public. We might make `plumbing` be `#[doc(hidden)]`, as well.
