### ISSUE TITLE
Merge DependencyStorage and MemoizedStorage?

### ISSUE THREAD

**Issue by matklad** [salsa-rs/salsa#18]
Currently, we have `MemoizedStorage` which, for each query, remembers a list of dependencies and the result value, and `DependencyStorage`, which remembers only dependencies (to save storage). 

They could be merged into an Storage which remembers deps and "optional" result. That way, we'll be able to implement smart strategies for evicting large unused results (something like LRU).

cc https://github.com/nikomatsakis/salsa/issues/7#issuecomment-425893534 and https://github.com/nikomatsakis/salsa/pull/14

**Comment by nikomatsakis** [comment]
Yeah, the fact that I started one by copying-and-pasting the other is usually a sign as well that a merge would make sense. =)

**Comment by matklad** [comment]
@nikomatsakis should I give it a shot?

The plan is, roughly:

* rename `DependencyStorage` to `WeakMemoizedStorate`
* change impl to store `Option<Value>`, and don't store values by default
* (???) add some kind of gc hook to allow the client to control if a value should be preserved or not.
* (???) dedupe `DependencyStorage` and `WeakMemoizedStorage` by using some value-level or type level parallelization.

**Comment by nikomatsakis** [comment]
@matklad Sure, though I'd leave the gc hook for later =) I had expected though to merge `DependencyStorage` and `MemoizedStorage` ultimately. If we want to statically configure things, we could have them be parameterized by some type of `StoragePolicy` type that configures the various bits.

e.g., when we have invoked the fn and we have a value, we could use `storage_policy.create_memoized_value(&user_value, changed_at)` and it would return a `Option<V>` (`None`, in the case of dependency only).

**Comment by matklad** [comment]
>and it would return a Option<V> (None, in the case of dependency only).

I was thinking about it returning a `Result<V, ()>` or `Result<V, Void>`, depending on the policy, but that is probably over engineering. Will look into this around the weekend then!
