### ISSUE TITLE
replace macros with custom derive or procedural macros?

### ISSUE THREAD

**Issue by nikomatsakis** [salsa-rs/salsa#20]
Currently we write things like:

https://github.com/salsa-rs/salsa/blob/e18f14fca5eefc4f104cca85dba3256e6811f9f2/tests/incremental/memoized_dep_inputs.rs#L13-L18

This has the downside that the contents are sort of "opaque" to tools like rustfmt etc, despite being obviously Rust code. Perhaps we should use a custom derive:

```rust
#[derive(salsa::query_definition)]
crate fn Memoized2(query: &impl MemoizedDepInputsContext, (): ()) -> usize {
    query.log().add("Memoized2 invoked");
    query.dep_memoized1().read()
}
```

The only sort of weird thing is that the result would not, in fact, be a function.

For that matter, we could go further and apply the derive at other levels.

**Comment by csmoe** [comment]
I'll take care of this to strengthen my learning of rust macros.

**Comment by csmoe** [comment]
@nikomatsakis seems already implemented in https://github.com/salsa-rs/salsa/pull/119 https://github.com/salsa-rs/salsa/pull/125 ?

**Comment by matklad** [comment]
Yup!
