### ISSUE TITLE
Gracefully handling cycle errors

### ISSUE THREAD

**Issue by lpil** [salsa-rs/salsa#214]
Hello!

Thanks for this library! It is super cool!

I'm trying Salsa out as a new heart for the compiler of my language [Gleam](https://github.com/gleam-lang/gleam). I've a tiny prototype here: https://github.com/lpil/learning/blob/c9cc72c2505dce2a142a7e67010e0b3e4cb8beaf/rust/salsa_test/src/main.rs

One piece of functionality that I was not able to replicate was graceful handling of import cycles. A programmer may mistakenly make a module import itself (either directly of through a chain of other modules). Wish Salsa this would be a query that depends upon itself, creating a cycle, and causing a panic.

How might I avoid panicking and instead return an error value in this situation wish Salsa? I think this may be the same as https://github.com/salsa-rs/salsa/issues/6, but I was unsure if there was another mechanism that could be used here.

Thanks,
Louis

**Comment by Marwes** [comment]
https://github.com/salsa-rs/salsa/pull/147 implements an approach which I use in https://github.com/gluon-lang/gluon exactly to cope with import cycles.

**Comment by lpil** [comment]
Wonderful! Thank you for your quick help @Marwes !

If I might ask you a quick off-topic question, does Gluon persist the database in some fashion so the previous cache can be used when the Gluon program is run a second time? To avoid recompilation of unchanged code.

**Comment by Marwes** [comment]
Not yet, something to be added eventually however.

**Comment by lpil** [comment]
Thank you.
