### ISSUE TITLE
`invalidate` a query doesn't make dependents recompute themselves.

### ISSUE THREAD

**Issue by lerencao** [salsa-rs/salsa#246]
I followed the guide of [on demand inputs](https://salsa-rs.github.io/salsa/common_patterns/on_demand_inputs.html).
But come across a problem that the other queries which depend on the on-demand input doesn't recompute themselves.

The following example reproduces it.

``` rust
    pub trait InputChangeNotifier {
        fn read(&self, key: u32) -> u32;
        fn did_change_value(&mut self, key: u32);
    }
    #[salsa::query_group(LazyInputTestStorage)]
    pub trait LazyInputQueryGroup: InputChangeNotifier {
        fn read_value(&self, key: u32) -> u32;
        fn mul2(&self, key: u32) -> u32;
    }

    fn read_value(db: &dyn LazyInputQueryGroup, key: u32) -> u32 {
        db.salsa_runtime()
            .report_synthetic_read(salsa::Durability::LOW);
        db.read(key)
    }
    fn mul2(db: &dyn LazyInputQueryGroup, key: u32) -> u32 {
        db.read_value(key) * 2
    }

    #[salsa::database(LazyInputTestStorage)]
    #[derive(Default)]
    pub struct TestDatabase {
        storage: salsa::Storage<Self>,
        numbers: HashMap<u32, u32>,
    }
    impl salsa::Database for TestDatabase {}
    impl InputChangeNotifier for TestDatabase {
        fn read(&self, key: u32) -> u32 {
            *self.numbers.get(&key).unwrap()
        }

        fn did_change_value(&mut self, key: u32) {
            ReadValueQuery.in_db_mut(self).invalidate(&key)
        }
    }
    impl TestDatabase {
        pub fn set_key(&mut self, k: u32, v: u32) {
            self.numbers.insert(k, v);
            self.did_change_value(k);
        }
    }

    #[test]
    pub fn test_invalidate() {
        let mut db = TestDatabase::default();

        // init
        db.set_key(1, 11);
        assert_eq!(db.read_value(1), 11);
        assert_eq!(db.mul2(1), 22);

        // invalidate key
        db.set_key(1, 111);
        // it's ok
        assert_eq!(db.read_value(1), 111);

        // but, this will fail.
        assert_eq!(db.mul2(1), 222);
    }


```

**Comment by lerencao** [comment]
After tracking down the code,I think a possible solution is: when invalidating a slot's memo, 
https://github.com/salsa-rs/salsa/blob/590c037323d7c4e6fba1a8cc88f60913d9e7a803/src/derived/slot.rs#L526
the `changed_at` revision can be set to incremented revision of runtime.
 https://github.com/salsa-rs/salsa/blob/590c037323d7c4e6fba1a8cc88f60913d9e7a803/src/derived.rs#L231

**Comment by jonas-schievink** [comment]
Swapping these two lines causes the assertion to fail:

https://github.com/salsa-rs/salsa/blob/114d6db8f6575de9b991c3ce9944f0a679a24b85/tests/on_demand_inputs.rs#L74-L75

Even setting `changed_at` as suggested above does not seem to fix that.

**Comment by jonas-schievink** [comment]
Ah, that happens because `report_synthetic_read` does not set `changed_at` to the current revision, so `AQuery` ends up with a `changed_at` value of `R1` while we're already in `R2`, and `BQuery` thinks it's fine to reuse its old value.

**Comment by jonas-schievink** [comment]
That doesn't really seem to be the right fix though, since it would lead to us always re-running the query that used `report_synthetic_read`.
