### ISSUE TITLE
bikesheds around conventions and macro names

### ISSUE THREAD

**Issue by nikomatsakis** [salsa-rs/salsa#26]
There are a few things I'd like to bikeshed about:

- I've been using the name `query` to represent the query context, but I think it may not be the best choice. It suggests that this is a *query* when indeed it is not, it is the overall context. Perhaps `context`? But that's so vague. `salsa`? `q`? I am trying not to wind up with something obscure like `tcx` from the compiler.
- What should we call the `salsa::query_prototype!` macro etc. When writing up the ["hello world README"](https://github.com/salsa-rs/salsa/blob/master/examples/hello_world/README.md) I felt like the overall terminology wasn't *ideal*. 
    - For `query_prototype` in particular, we don't use the term prototype anywhere else.

I think I'd prefer some name -- maybe "query context" is good -- that consistent refers to the **traits** and some other name for the **struct that implements them**. I had been calling that struct the "storage" but that's really just a "subpart" of the struct. "Query context implementation" is a bit verbose.

Thoughts?

**Comment by matklad** [comment]
I've been thinking about QueryContext as "Database", so I suggest using `db` as a name for the user-visible context struct: `fn GetType(db: impl DeclarationsDb + UseDefDb, expr: ExprId)`

**Comment by nikomatsakis** [comment]
Ooh, I like database.

**Comment by nikomatsakis** [comment]
I was also thinking that we could have a name like "query group" to describe the set of queries that are grouped together into one trait. So that would leave:

- database: the final struct that implements all the traits
- database storage: the struct that stores the data for all the queries
- query group: each of the traits that define a group of queries
- query definition: the implementation of the queries

So you'd have something like this:

```
salsa::query_group! {
    trait TypeCheckerDatabase: salsa::Database {
        fn foo() for Foo;
    }
}

salsa::query_definition! {
    Foo(db: &impl TypeCheckerDatabase, key: K) -> V { ... }
}

struct MyDatabase {
    runtime: salsa::Runtime<MyDatabase>,
}

salsa::database_storage! {
    struct MyDatabaseStorage for MyDatabase { .. }
}
```

**Comment by matklad** [comment]
what about `query_declaration` instead `query_group`? That is, use C's declaration/definition split?

**Comment by nikomatsakis** [comment]
Hmm. Maybe, I liked group because it is a good term for what the *trait itself* represents (that is, query declaration sounds like it's talking about an individual query). I think it's useful to have a term that is talking about a "block" of queries that are defined together. I'd be inclined to do `query_declarations!` if we went that route, and that seems a bit more clumsy.

**Comment by nikomatsakis** [comment]
Another question: I sometimes want to give the key/value pairs when defining the `query_group`. I didn't set it up that way because it's less DRY, since the definition also specifies them (and naturally they would have to agree), but it feels like it's nicer as a reader to see the key/value pairs. This is particularly true since we often write the comments when defining the group. Thoughts?

**Comment by matklad** [comment]
Should we close the issue? The API is now much nicer and doesn't have any obvious problems.

**Comment by nikomatsakis** [comment]
I think so. Great!
