### ISSUE TITLE
Host videos on other websites as well

### ISSUE THREAD

**Issue by Evian-Zhang** [salsa-rs/salsa#278]
As a Chinese rust developer, I am very interested in how salsa works. However, I could not view the videos about salsa on YouTube since it is unaccessible for me. Could you provide these videos on other websites which can be accessed by Chinese network as well?

**Comment by nikomatsakis** [comment]
What is an example of such a site?

**Comment by armoha** [comment]
Uploaded videos on bilibili (I don't have China phone number so couldn't register Youku)

How Salsa Works: https://www.bilibili.com/video/BV1Df4y1A7t3/
Salsa In More Depth: https://www.bilibili.com/video/BV1AM4y1G7E4/

**Comment by Evian-Zhang** [comment]
@armoha Thank you!

**Comment by nikomatsakis** [comment]
I'm reopening the issue to suggest adding links to those videos into the book/readme/etc
