### ISSUE TITLE
have salsa `query_prototype` declaration macro also create storage

### ISSUE THREAD

**Issue by nikomatsakis** [salsa-rs/salsa#28]
I was thinking that we should refactor the `query_prototype` macro so that it also generates a **storage struct** for all the queries defined within the trait. So something like this:

```rust
query_prototype! {
    trait Foo: salsa::QueryContext {
        fn bar() for Bar();
        fn baz() for Baz();
    } in struct FooStorage; // <-- give the name of the storage struct here
}
```

Here the `FooStorage` struct would define fields `bar` and `baz` with the storage for those queries. Then when we define the complete query context storage, we need only reference the `FooStorage` type:

```rust
query_context_storage! {
    struct QueryContextStorage {
        FooStorage
    }
}
```

In particular, we don't have to list out all the queries in `Foo` again. This is nice for two reasons:

- More DRY
- You can implement two "query context traits" (query groups, whatever) that have overlapping names for methods -- only the *query groups* have to have unique names.

I remember that in the shower I had a sort of elaborate scheme involving a generic `Get<T>` trait as well, that would allow you to get the storage fields without having to name the actual field, but I can't remember exactly what I was thinking.

Anyway, I'm not sure 100% of the setup — I'd like to avoid having to give a name to the storage type, for example, though I don't see an obvious alternative — but I feel like *something* in this direction would be nice.

**Comment by matklad** [comment]
> I don't see an obvious alternative

This is horrible and I am not sure will work, but, if we have a trait `$name`, I think we can use type-level function to name a storage?

That is, the macro will generate something like the following 

```
impl StorageType for dyn $name {
    type Storage = ($($query,)*);
}
```

and then we can refer to storage type using trait name as `<dyn $name as StorageType>::Storage`.

**Comment by nikomatsakis** [comment]
I considered a scheme like, but I don't think the traits will be object-safe.

**Comment by nikomatsakis** [comment]
Investigating this, I realized there is one other complication: the descriptor type is a giant enum with one variant per query. It really wants to be generated at the same time as the complete database — or at least we'd have to introduce a kind of "two-level descriptor" that ranges over the query groups and then have a per-group descriptor. I guess that'd be ok.

**Comment by matklad** [comment]
Now having used salsa quite a bit in rust-analyzer, I must say that explicitly mentioning every query storage (as opposed to just the trait) is annoying :)

**Comment by kleimkuhler** [comment]
In making the new test file for panic safety I had a similar thought to something like this existing! I essentially copy-pasted another test file and changed the query names/storage. I think it'd be great to have :)

**Comment by nikomatsakis** [comment]
I'm marking this "high priority" because I think this is the next major thing to resolve. Have to ponder it a bit but I guess the basic schemes I was describing before are still the best idea I have.

**Comment by nikomatsakis** [comment]
Hmm. This is still relevant, but awfully old. Closing for now.
