### ISSUE TITLE
Is Salsa still experimental?

### ISSUE THREAD

**Issue by mheiber** [salsa-rs/salsa#284]
The README says:

"Very much a WORK IN PROGRESS at this point. Ready for experimental use but expect frequent breaking changes."

However, Rust Analyzer is widely used and Salsa [is a core prod dependency](https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/dev/architecture.md).

Is it safe to remove the "experimental" wording? I worry the "experimental" could unnecessarily scare people off.

How about this alternative wording, would it better-represent the current state of the project?

- "Salsa is ready for use in production, but expect frequent breaking changes."

> Thank you for maintaining this fine project

**Comment by 8573** [comment]
> If you need 100% correctness, you shouldn't use salsa yet.

If you don't mind my curiosity, are the correctness problems more from optimizations or from incrementalization being fundamentally difficult to implement correctly?

**Comment by matklad** [comment]
The latter. Specifically, handling *recoverable* cycles incrementally is just hard arithmetically, and both salsa and rustc had a fair share of bugs when cycles and incr comp meet. 

Though, I believe that that specific bug was actually fixed in the meantime?
