### ISSUE TITLE
Implement garbage collection: when a tracked struct is not created in new round, delete

### ISSUE THREAD

**Issue by nikomatsakis** [salsa-rs/salsa#315]
When a tracked function executes, we also track what tracked structs it creates. When it re-executes, we can delete any tracked structs that were not created the second time, and we can also go and delete the values of their fields -- as well as tracked functions defined against them (but that is a bit more complex and should be moved into a new section). This will help keep memory use under control.

**Comment by 8573** [comment]
In terms of balancing saving memory vs saving recomputation, how does such garbage collection compare to keeping the structs in a cache of fixed capacity?

> When it re-executes, we can delete any tracked structs that were not created the second time

I don't know enough to say, but is this implying that structs not computed the second time should not be needed again? What if Salsa is powering an LSP server the user of which deletes a large chunk of code, rewrites that code in a different way, and then changes their mind and "Undo"es back to the original code?

I apologize in advance if my uninformed questions are too uninformed or irrelevant.

**Comment by jonas-schievink** [comment]
Undoing edits to arrive at an earlier state already requires computing everything that changed again with current-day salsa and is unlikely to change (the amount of recomputation is typically very small).

**Comment by nikomatsakis** [comment]
I'm working on this -- as part of fixing #338 and #313 I'm realizing that I likely have to add all the infra we need here.
