### ISSUE TITLE
Add "builder style" setter APIs that permit setting durability

### ISSUE THREAD

**Issue by nikomatsakis** [salsa-rs/salsa#329]
The `salsa::input` structs generate a setter for each field. We should make an alternate version of the setter that takes a durability. The obvious thing is something like `set_foo_with_durability`, but now that I think about it, maybe a builder API would be more appropriate, in order to be more future proof.

I'm inclined to modify the setters to be builder style. You would write `input.set_foo(&mut db)` and that would return a `salsa::Setter` struct that captures the input, a reference to the field (a `FunctionIngredient`), and the database. The setter would have a `to_value(self, value)` that stores the new value, so that the "normal" call looks like

```rust
input.set_foo(&mut db).to_value(value)
```

but then we can add additional builder style methods, e.g.

```rust
input.set_foo(&mut db).with_durability(Durability::HIGH).to_value(value)
```

This makes those method highly discoverable and easily documented. It also means we can add new "final actions", e.g. maybe for "taking", deleting, or something else in the future.

**Comment by nikomatsakis** [comment]
I'm tagging this as good-first-issue, although it does involve some exploration. The instructions [in this issue](https://github.com/salsa-rs/salsa/issues/327#issuecomment-1207233655) show the code how input-field setters are implemented and also what happens at runtime. For this issue, I think we would want to introduce some support code into the salsa-2022 crate, basically a `salsa_2022::setter` module and a `Setter` type. It would be generic over the input entity type and the function ingredient.

**Comment by dawnofmidnight** [comment]
Hi, could I try tackling this?
