### ISSUE TITLE
Add options to tracked functions for cycle recovery

### ISSUE THREAD

**Issue by nikomatsakis** [salsa-rs/salsa#331]
Salsa allows tracked functions to declare a "cycle recovery" function, [as described here](https://salsa-rs.github.io/salsa/cycles/fallback.html) (actually, that page is somewhat out of date, we no longer require all cycle participants to define a recovery function, for example, should fix that --ed.). This capability is not exposed yet for tracked functions. 

We should support users writing something like

```rust
#[salsa::tracked(recovery_fn = my_recover_fn)]
fn my_tracked_fn(db: &dyn crate::Db, ...) { }

fn my_recover_fn(
    db: &dyn MyDatabase,
    cycle: &salsa::Cycle,
) -> MyResultValue
```

**Comment by nikomatsakis** [comment]
I'm tagging as good first issue. Here are some mentoring instructions for how to do it.

### Step 0: Add a failing test

Create a test in the `salsa-2022-tests/tests` directory that creates a cycle and which would benefit from fallback. You could actually port the [old cycles test file](https://github.com/salsa-rs/salsa/blob/master/tests/cycles.rs), or at least create a bit of its structure, but only copy a single case.

It's a good idea to get a failing test first, especially for testing the attribute macros. You can now add int he `recovery_fn` attribute that we want to work, even though it won't.

Now add in 

### Step 1: Add the `recovery_fn` option

First, you need to add the `recovery_fn` option. The options accepted by salsa attribute macros are defined by the `Options` struct defined in the salsa-2022-macros crate:

https://github.com/salsa-rs/salsa/blob/03a27a7054ee234a566231243dd5025edfbcdde6/components/salsa-2022-macros/src/options.rs#L5-L10

You'll need to add another field there, similar to the `db_path` field:

https://github.com/salsa-rs/salsa/blob/03a27a7054ee234a566231243dd5025edfbcdde6/components/salsa-2022-macros/src/options.rs#L33-L36

You'll also need to add code to parse it, similar to the code for `db_path`:

https://github.com/salsa-rs/salsa/blob/03a27a7054ee234a566231243dd5025edfbcdde6/components/salsa-2022-macros/src/options.rs#L149-L161

You'll also need to add a boolean to the `AllowedOptions` trait that the various macros use to define which options they accept;

https://github.com/salsa-rs/salsa/blob/03a27a7054ee234a566231243dd5025edfbcdde6/components/salsa-2022-macros/src/options.rs#L62-L70

The value of this field should generally be `false` except for on tracked functions:

https://github.com/salsa-rs/salsa/blob/03a27a7054ee234a566231243dd5025edfbcdde6/components/salsa-2022-macros/src/tracked_fn.rs#L61

### Step 2: Modify `tracked_fn` macro to use it

Now that the macro accepts the option, we need to use it a bit. For reference, [here](https://github.com/salsa-rs/salsa/blob/03a27a7054ee234a566231243dd5025edfbcdde6/components/salsa-macros/src/query_group.rs#L513-L531) is the old salsa code that uses a similar option (called `cycle`). 

In the new code, there is some setup for using the option, but it's not connected. The `Configuration` struct is used to define tracked functions...

https://github.com/salsa-rs/salsa/blob/03a27a7054ee234a566231243dd5025edfbcdde6/components/salsa-2022-macros/src/configuration.rs#L1-L9

...and you can see that it has `cycle_strategy` and `recover_fn` fields.

When the `recovery_fn` attribute is set, we need to set `cycle_strategy` to [`Fallback`](https://github.com/salsa-rs/salsa/blob/03a27a7054ee234a566231243dd5025edfbcdde6/components/salsa-2022-macros/src/configuration.rs#L38), and then we need to override `recover_fn` to invoke the function the user gave -- [exactly like the one from the older salsa code](https://github.com/salsa-rs/salsa/blob/03a27a7054ee234a566231243dd5025edfbcdde6/components/salsa-macros/src/query_group.rs#L517-L524). 

The `Configuration` for tracked functions is created in the `fn_configuration` function:

https://github.com/salsa-rs/salsa/blob/03a27a7054ee234a566231243dd5025edfbcdde6/components/salsa-2022-macros/src/tracked_fn.rs#L126

and you can see e.g. where we set the `execute` function:

https://github.com/salsa-rs/salsa/blob/03a27a7054ee234a566231243dd5025edfbcdde6/components/salsa-2022-macros/src/tracked_fn.rs#L154-L164

We need to do something similar, but for  `recover_fn`, except that we want to invoke the fallback function and we don't need to worry about finding the ingredients etc. Basically we want a function [exactly like the one from the older salsa code](https://github.com/salsa-rs/salsa/blob/03a27a7054ee234a566231243dd5025edfbcdde6/components/salsa-macros/src/query_group.rs#L517-L524). 

### Step 3: Fix your test, add more

The final step is to get the failing test you added in the beginning to work, and then port over these old salsa tests, which test a lot of combinations:

https://github.com/salsa-rs/salsa/blob/master/tests/cycles.rs

**Comment by XFFXFF** [comment]
I'm working on it
