### ISSUE TITLE
Permit renaming getters, setters, and constructors

### ISSUE THREAD

**Issue by nikomatsakis** [salsa-rs/salsa#332]
It's sometimes annoying that salsa defines the `new` function along with all the getters and setters. I've sometimes wanted to override them, e.g. to accent any `impl Into<Foo>` instead of just `Foo`. We should permit users to override them in some way. I am imagining a `#[method_names(foo=bar, ...)]` attribute that can be placed on the struct or on fields, e.g.

```rust
#[salsa::interned]
#[method_names(new = from_string)]
struct Id {
    #[method_names(get = raw_text)] #[return_ref]
    text: String
}

impl Id {
    pub fn new(db: &dyn crate::Db, s: impl Display) {
        Id::from_string(db, s.to_string())
    }

    pub fn text(self, db: &dyn Crate::Db) -> &str {
        self.raw_text(db)
    }
}
```

**Comment by XFFXFF** [comment]
Some discussion about API changes on zulip, paste here  
https://salsa.zulipchat.com/#narrow/stream/146365-good-first-issue/topic/.23332.20permit.20renaming.20constructors.2C.20getters.20and.20setters
