### ISSUE TITLE
Support singleton inputs

### ISSUE THREAD

**Issue by nikomatsakis** [salsa-rs/salsa#337]
[Zuo Baoquan points out that singleton inputs would be convenient](https://salsa.zulipchat.com/#narrow/stream/145099-general/topic/Access.20input.20without.20handle.3F). A proposed API looks something like this:

```rust
#[salsa::input(singleton)]
struct Configuration {
    verbose: bool
}
```

With the `singleton` option, there is only ever a single input in existence. You create it with `Configuration::new` (perhaps we should rename it, not sure, but let's separate that question):

```rust
let c1 = Configuration::new(&mut db, false); // verbose is false by default
```

You can then get back the global value by `Configuration::get`...

```rust
let c2: Option<Configuration> = Configuration::get(&db);
assert_eq!(Some(c1), c2);
```

...this will return `None` if the configuration is not yet created.

Like any input you can modify its fields, triggering a new revision:

```rust
c1.set_verbose(&mut db, true);
assert_eq!(c1.verbose(&db), true);
```

You can also invoke `new` again. Since the value already exists, that just updates its fields:

```rust
let c3 = Configuration::new(&mut db, false);
assert_eq!(c1, c3); // same instance as before is returned
assert_eq!(c3.verbose(&db), false); // field is updated
```

**Comment by nikomatsakis** [comment]
A bit of bike-shedding is needed.

Some questions

### Should `get` return `Option<Configuration>` or just `Configuration`?

Reading the verbose field is kind of painful...

```rust
Configuration::get(&db).unwrap().verbose(&db)
```

It might be nice if `get` returned `Configuration`, so you don't have to write `::get(&db).unwrap()`...

```rust
Configuration::get(&db).verbose(&db)
```

If we did that, it'd probably be nice to have *some* way to test if the result is initialized, maybe add a method with a different name, like `try_get`?

### Convenience getters

Even this is kind of long...

```rust
Configuration::get(&db).verbose(&db)
```

...might be nice to write `Configuration::verbose(&db)`, or something similar.

### new vs init

Maybe instead of `Configuration::new` we should write `Configuration::init`, and maybe it should panic if already initialized?

**Comment by nikomatsakis** [comment]
Personally, I'm somewhat inclined towards consistency -- making it easier to convert code that was non-singleton into singleton and vice-versa. I have a vague hunch that there will be times when you don't know yet if the singleton has been initialized or not, so making `new` simply reinitialize fields would be more convenient. 

This leads me to:

* `new`, not `init`
* re-initialize, not panic
* prefer normal getters, so `c.verbose(&db)` should work

But I also think convenience is key, so...

* `Configuration::get(&db)` should unwrap by default, with `try_get(&db)` offered as an alternative
* `Configuration::get_verbose(&db)` would be a nice shorthand

**Comment by nikomatsakis** [comment]
Precise details of the API aside, I'm tagging as good first issue and adding some mentoring instructions.

Warning that this will be slightly involved and may involve some bikeshedding and updating of PR as to the precise details.

Add `singleton` to the `Options` struct...

https://github.com/salsa-rs/salsa/blob/03a27a7054ee234a566231243dd5025edfbcdde6/components/salsa-2022-macros/src/options.rs#L10

...since it's a flag, you can model it on the `no_eq` field...

https://github.com/salsa-rs/salsa/blob/03a27a7054ee234a566231243dd5025edfbcdde6/components/salsa-2022-macros/src/options.rs#L16-L20

...and it must also be added to the `AllowedOptions` trait...

https://github.com/salsa-rs/salsa/blob/03a27a7054ee234a566231243dd5025edfbcdde6/components/salsa-2022-macros/src/options.rs#L63-L70

...and set to `false` for everything except for `salsa::input`. `salsa::input` uses the same allowed options as all salsa structs though...

https://github.com/salsa-rs/salsa/blob/03a27a7054ee234a566231243dd5025edfbcdde6/components/salsa-2022-macros/src/salsa_struct.rs#L38-L50

There are two options here:

* Modify `SalsaStruct` to be generic over a mode (e.g., `SalsaStruct<Tracked>`, etc), which actually might be a nice refactoring and would be a good first PR.
* Add some code in the other salsa structs to check for and report an error if the option is used (less good, easier).

Next you have to modify the generated code a bit.

The `new` function is here:

https://github.com/salsa-rs/salsa/blob/03a27a7054ee234a566231243dd5025edfbcdde6/components/salsa-2022-macros/src/input.rs#L96-L105

I'd probably change the call to `new_input`...

https://github.com/salsa-rs/salsa/blob/03a27a7054ee234a566231243dd5025edfbcdde6/components/salsa-2022-macros/src/input.rs#L100

... to call a new method called `new_singleton_input`, and then add that method to [`InputIngredient`](https://github.com/salsa-rs/salsa/blob/03a27a7054ee234a566231243dd5025edfbcdde6/components/salsa-2022/src/input.rs#L12). `new_singleton_input` would just check if an input already exists and return that, and otherwise create a new one.

Then you need to add the `get` method. Here I'd add a method to [`InputIngredient`] like `get_singleton_input` that returns `Option<Id>`, returning `None` if `self.counter == 0` but otherwise returning `Some(self.new_singleton_input())` :)

Then you have to add the user-facing method in procedural macro by adding a new inherent method into this impl:

https://github.com/salsa-rs/salsa/blob/03a27a7054ee234a566231243dd5025edfbcdde6/components/salsa-2022-macros/src/input.rs#L95

...something like

```rust
#[track_caller]
pub fn get(__db: &#db_dyn_ty) -> Self {
    let (__jar, __runtime) = <_ as salsa::storage::HasJar<#jar_ty>>::jar(__db);
    let __ingredients = <#jar_ty as salsa::storage::HasIngredientsFor< #ident >>::ingredient(__jar);
    __ingredients.#input_index.get_singleton_input(__db).expect("singleton not yet initialized")
}
```

(The `#[track_caller]` annotation tells Rust to put the "blame" for the `expect` failure on the caller to `get`, not the `get` method itself.)

**Comment by 1ntEgr8** [comment]
@nikomatsakis I would like to take this on

**Comment by nikomatsakis** [comment]
@1ntEgr8 great! Let me know if you have questions. 

Probably best to ping on Zulip as I'm not so great at keeping up with GH notifications these days.
