### ISSUE TITLE
Add options to tracked funcitons for lru capacity

### ISSUE THREAD

**Issue by XFFXFF** [salsa-rs/salsa#344]
The [set_lru_capacity](https://docs.rs/salsa/0.16.1/salsa/struct.QueryTableMut.html#method.set_lru_capacity) method, in old salsa, can be used to fix the maximum capacity for a query. In salsa-2022, we already have a method [`set_capacity`](https://github.com/salsa-rs/salsa/blob/367c0bfe1154d8848600bf4029343882652a358c/components/salsa-2022/src/function.rs#L151) to do the same thing, but without exposing the api to users.  

We could support users writing somthing like

```rust
#[salsa::tracked(lru_capacity=32)]
fn my_tracked_fn(db: &dyn crate::Db, ...) { }
```  

cc @nikomatsakis

**Comment by nikomatsakis** [comment]
Yes! I was actually just coming to file this issue. A few notes:

* lru should not be combined with specify. We should report an error if people do `#[salsa::tracked(lru = 32, specify)]`. 
* Maybe we want to just write `lru = 32` and not `lru_capacity = 32`?
* Maybe we want a default capacity? Nah, not worth it.
