### ISSUE TITLE
Clear `deleted_entries` when a new revision starts

### ISSUE THREAD

**Issue by XFFXFF** [salsa-rs/salsa#348]
https://github.com/salsa-rs/salsa/blob/648248bd39aec8e4e22467aefd80a285830ca634/components/salsa-2022/src/storage.rs#L91-L102  
https://github.com/salsa-rs/salsa/blob/648248bd39aec8e4e22467aefd80a285830ca634/components/salsa-2022/src/function.rs#L225-L233
Every time a new revision starts, we invoke `reset_for_new_revisions` on all `mut_routes` to clear the `deleted_entries`. But it seems we are not pushing anything to `mut_routes` for function ingredients, it is always empty, so `reset_for_new_revisions` is not called

**Comment by nikomatsakis** [comment]
@XFFXFF yes! I found (and fixed) that in #349
