### ISSUE TITLE
Add an API to mock some input of durability has changed.

### ISSUE THREAD

**Issue by XFFXFF** [salsa-rs/salsa#364]
`synthetic_write` in old salsa causes the system to act *as though* some  input of durability `durability` has changed. Maybe we should support it in salsa-2022 too. 
https://github.com/salsa-rs/salsa/blob/80d0d141945051ec86ecd979ac06cca1e364b27e/src/runtime.rs#L100-L110

**Comment by nikomatsakis** [comment]
Yeah, it's useful for testing. Let's do it. Not sure why I left it out.
