### ISSUE TITLE
tutorial outdated: `parse_statements` is not tagged with `#[salsa::tracked(return_ref)]` anymore

### ISSUE THREAD

**Issue by zjp-CN** [salsa-rs/salsa#380]
book: https://github.com/salsa-rs/salsa/blob/9677935c9cec554b7a5bc182be71f668d5b0e96f/book/src/tutorial/parser.md#the-return_ref-annotation
code: https://github.com/salsa-rs/salsa/commit/590c5ce8d3f5f276815886d5ebe9cc2aac7a5162#diff-f1322f83136cea2982602341b0c54e65146ccda2b2c17015da7d57e4fa6acfccL9

**Comment by seanchen1991** [comment]
Thanks for pointing this out! https://github.com/salsa-rs/salsa/pull/375#discussion_r953020069 addresses this 🙂
