### ISSUE TITLE
Add an API like `new_with_durability` to construct input with specific durability

### ISSUE THREAD

**Issue by xffxff** [salsa-rs/salsa#385]
https://github.com/salsa-rs/salsa/pull/362 added "builder style" setter APIs that permit setting durability. I think it's a little inconvenient to use it

```rust
#[salsa::input] 
struct MyInput {
   field1: u32;
   field2: u32;
}

let input = MyInput::new(&mut db, 1, 2);
input.set_field1(&mut db).with_durability(Durability::HIGH).to(1);
input.set_field2(&mut db).with_durability(Durability::HIGH).to(2);
```
* We give `field1` the value `1` when we `new` the input, but if we want to set the durability, we also need to assign it to `1` again via `to(1)`, same for `field2`
* When there are many fields, we need to set the durability one by one.

Could we have an API like `new_with_durability` to construct input with specific durability? Use it like
```rust
MyInput::new_with_durability(&mut db, field1, field2, Durability::HIGH)
```

**Comment by nikomatsakis** [comment]
Maybe we can have a builder style API for creating inputs, too, to give room for future options?

I think I would keep `new` as a shorthand, and to ensure that the 'basic methods' for all salsa structs are the same:

* new to create
* getters to read

but something like `MyInput::new_builder(&mut db).with_durability(HIGH).with_fields(1, 2)` could work?

**Comment by XFFXFF** [comment]
> Maybe we can have a builder style API for creating inputs, too, to give room for future options?

Yes, I think a builder stayle API is great

**Comment by mdx97** [comment]
Is the durability supposed to be able to vary between the fields in a struct? If so, it might make sense to implement some sort of builder API for field values themselves:
```rust
let input = MyInput::new(
    &mut db,
    InputFieldBuilder::new(1)
        .with_durability(Durability::HIGH),
    InputFieldBuilder::new(2)
        .with_durability(Durability::MEDIUM),
);
```
