### ISSUE TITLE
`debug` method for `DependencyKeyIndex` should leverage `DebugWithDb` 

### ISSUE THREAD

**Issue by nikomatsakis** [salsa-rs/salsa#386]
In #369, @zjp-CN added a debug method for `DependencyKeyIndex` that is (more) human-readable. In #378, @agluszak improved the `DebugWithDb` impl for salsa structs. We should put these together! Right now if you have a struct like

https://github.com/salsa-rs/salsa/blob/1363d78fe5fa85a7f92ee03ad366559b983454b2/salsa-2022-tests/tests/deletion-cascade.rs#L38-L41

and a function like

https://github.com/salsa-rs/salsa/blob/1363d78fe5fa85a7f92ee03ad366559b983454b2/salsa-2022-tests/tests/deletion-cascade.rs#L51-L55

you wind up with output like

https://github.com/salsa-rs/salsa/blob/1363d78fe5fa85a7f92ee03ad366559b983454b2/salsa-2022-tests/tests/deletion-cascade.rs#L124

but it would be more readable if we got `contribution_from_struct(MyTracked { salsa::id: 2 })`.

Another case to consider are functions with multiple inputs. They'll be touch tricker because they first intern those inputs.

**Comment by nikomatsakis** [comment]
Brief mentoring instructions:

The code that generates the output in question is here:

https://github.com/salsa-rs/salsa/blob/1363d78fe5fa85a7f92ee03ad366559b983454b2/components/salsa-2022/src/function.rs#L276-L278

The simplest fix would be to modify the `fmt_index` helper function:

https://github.com/salsa-rs/salsa/blob/1363d78fe5fa85a7f92ee03ad366559b983454b2/components/salsa-2022/src/ingredient.rs#L68-L79

so that instead of taking a `salsa::Id` it took a `Option<impl DebugWIthDb>`, and then (in the function ingredient) to convert the `salsa::Id` into a `C::Key` using this method:

https://github.com/salsa-rs/salsa/blob/1363d78fe5fa85a7f92ee03ad366559b983454b2/components/salsa-2022/src/function.rs#L118-L122

This will work for the example above, but it won't work for a function with multiple inputs. To handle *that* case... hmm.... that will be harder, because the interning actually takes place outside of the function ingredient. The macro creates an interner:

https://github.com/salsa-rs/salsa/blob/1363d78fe5fa85a7f92ee03ad366559b983454b2/components/salsa-2022-macros/src/tracked_fn.rs#L376

and the function ingredient has no link to it. I'm not sure how to handle that yet! Probably we have to move that interning into the function ingredient as a refactoring. But no reason not to handle the first case nicely to start.

**Comment by OLUWAMUYIWA** [comment]
I'd like to pick this up.

**Comment by nikomatsakis** [comment]
@OLUWAMUYIWA Great! Let me know if you need any help.

**Comment by nikomatsakis** [comment]
I'm thinking about this -- I wonder if we truly want to use the `DebugWithDb` impl, or if we want to add methods to the `SalsaStructInDb` trait. My concern is that we definitely do not want to be printing out things that are not part of the 'identity' of the struct -- e.g., reading tracked struct fields that are not `#[id]`, or input struct fields. That could have unexpected side-effects or cause bugs, since those reads would be registered as reads of the active query.

**Comment by nikomatsakis** [comment]
This makes it a little tricker, but not too bad I don't think. We have to add some new methods to `DebugWithDb` that generate a more limited print-out.

**Comment by OLUWAMUYIWA** [comment]
Okay sure. I'll add another method to `DebugWithDb` that prints just the struct name and `id`, yeah?

Another thing. Does this change to `fmt_index` need to be made  for all Salsa structs? All of them delegate the `fmt_index` helper function to implement the `fmt_index` associated method of the `Ingredients` trait. 
I realized that I might need to change the function signature to include a `&DB` so I can use the `DebugWithDb` to print (by calling index.debug(&db)). That requires another trait bound on the `DB` type parameter on the `Ingredients` trait. It currently only has `?Sized`. I'd need to add `+Database`.

Or, am I getting this wrong, @nikomatsakis ?
Thanks!

**Comment by nikomatsakis** [comment]
@OLUWAMUYIWA 

I'm not entirely sure what would be best! Here are the two considerations:

* We do not want to be printing anything that's not part of the "identity" of the struct. That's potentially *more* than just the `#[id]`, at minimum it includes the field marked as `#[id]` on a tracked struct (and I think users should be able to "opt in" for inputs and things as well). Now, in #397, I noted that the same thing applies to `DebugWithDb`, so we could potentially just use that.
* But we'd also like users to be able to supply their own `DebugWithDb` impls and customize how it works! In the case of a tracing event, it might really lead to bad behavior, so maybe it's worth having a separate callback that is specific to `DependencyKeyIndex` and not customizable by end-users.

I'm not sure yet!

**Comment by nikomatsakis** [comment]
No longer relevant.
