### ISSUE TITLE
Panic when reading fields of tracked structs from older revisions

### ISSUE THREAD

**Issue by XFFXFF** [salsa-rs/salsa#407]
```rust
use test_log::test;

#[salsa::jar(db = Db)]
struct Jar(MyInput, MyTracked, final_result, intermediate_result);

trait Db: salsa::DbWithJar<Jar> {}

#[salsa::input(jar = Jar)]
struct MyInput {
    field: u32,
}

#[salsa::tracked(jar = Jar)]
struct MyTracked {
    field: u32,
}

#[salsa::tracked(jar = Jar)]
fn final_result(db: &dyn Db, tracked: MyTracked) -> u32 {
    tracked.field(db) * 2
}

#[salsa::tracked(jar = Jar)]
fn intermediate_result(db: &dyn Db, input: MyInput) -> MyTracked {
    MyTracked::new(db, input.field(db) / 2)
}

#[salsa::db(Jar)]
#[derive(Default)]
struct Database {
    storage: salsa::Storage<Self>,
}

impl salsa::Database for Database {}

impl Db for Database {}


#[test]
fn execute() {
    let mut db = Database::default();

    let input = MyInput::new(&mut db, 22);
    let tracked = intermediate_result(&db, input);

    dbg!(final_result(&db, tracked));

    input.set_field(&mut db).to(24);
    dbg!(final_result(&db, tracked));
}
```
it will output
```sh
[salsa-2022-tests/tests/hello_world.rs:46] final_result(&db, tracked) = 22
[salsa-2022-tests/tests/hello_world.rs:49] final_result(&db, tracked) = 22
```
not sure if this is expected behavior, or if we should get
```sh
[salsa-2022-tests/tests/hello_world.rs:46] final_result(&db, tracked) = 22
[salsa-2022-tests/tests/hello_world.rs:49] final_result(&db, tracked) = 24
```

**Comment by nikomatsakis** [comment]
@XFFXFF Actually, I believe the expected behavior *should* be a panic -- I've been meaning to open an issue about this!

**Comment by nikomatsakis** [comment]
So, the problem in this example is that it is bogus to take a tracked struct from an older revision and continue using it after altering the inputs. However, we don't detect this! And even simpler test would just be to read:

```
dbg!(tracked.field(db));
```

That will currently print `22` but should (imo) panic.

The offending code is this case:

https://github.com/salsa-rs/salsa/blob/f0fe691d3f902fab4ea3f419ea4f7493b46a5030/components/salsa-2022/src/function/maybe_changed_after.rs#L173-L178

`QueryOrigin::Field` should act the same as `QueryOrigin::Assigned`, I believe:

https://github.com/salsa-rs/salsa/blob/f0fe691d3f902fab4ea3f419ea4f7493b46a5030/components/salsa-2022/src/function/maybe_changed_after.rs#L165-L172

This would indicate that the value is considered dirty. Attempting to execute the function will panic.

Alternatively, I think we could just panic immediately in `maybe_changed_after` -- that might even be better. The panic message would be something like "accessing field of tracked struct `{:?}` from older revision".

**Comment by nikomatsakis** [comment]
@XFFXFF would you be up to take a crack at fixing this?

**Comment by XFFXFF** [comment]
> would you be up to take a crack at fixing this?

Yes, I'd love to
