### ISSUE TITLE
Singleton inputs: best behavior when a new instance is created?

### ISSUE THREAD

**Issue by nikomatsakis** [salsa-rs/salsa#415]
What is the best behavior when a second instance of a singleton is created?

Options:

* Panic!
* Overwrite the fields of the first one!

Right now, we do the second. Doing an extremely scientific study ([looking at the first google hit](https://www.digitalocean.com/community/tutorials/java-singleton-design-pattern-best-practices-examples#lazy-initialization)) I see that the typical Java pattern is to return the existing object, but they don't address the question of whether it has fields.

(_Originally posted by @nikomatsakis in https://github.com/salsa-rs/salsa/issues/404#issuecomment-1247902050_)

**Comment by nikomatsakis** [comment]
I am leaning towards panicking right now, and here is why:

With the current setup, where the fields get overwritten, singleton inputs have this odd edge case that the `new` method mutates the values of existing fields, but that doesn't happen for other inputs. This keeps coming up as a consideration:

@Skepfyr encountered it when adding support for on-demand inputs, and had to make the constructor take `&mut`.

@OLUWAMUYIWA encountered it in #414 when adding support for immutable fields to inputs. 

Seems like a nasty edge case to me.

**Comment by Skepfyr** [comment]
I'd definitely prefer panicking over modifying the value. Singletons feel to me like the salsa equivalent of a `OnceCell` in a const/static; `OnceCell::set` returns a `Result<(), T>`, so this change would make `new(val)` look more like `once.set(val).unwrap()`.

I do wonder in general if salsa should return `Result`s in more places and let the user decide, but I think that's a bigger design question that should be solved more holistically (and I want to noodle on it for a while).

**Comment by nikomatsakis** [comment]
OK, it seems we're in agreement on panics. #414 closes this issue.
