### ISSUE TITLE
[QUESTION] How can I reuse tracked function results in same revision?

### ISSUE THREAD

**Issue by Chronostasys** [salsa-rs/salsa#427]
Hi, I'm using salsa_2022 in my personal compiler project.   
Let's say I have 3 source files, `a` `b` and `c`. `a` depends on both `b`  and `c`, `b` depends on `c`.  
I defined an input struct contains a map from filename to content, and in the first tracked function `compile`, I create `FileCompileInput` (which is a tracked struct), and call another tracked function `compile_file`.   
When the input file `a` changes, `compile_file` will only be re-executed once for file `a`, which is working as expected. 
However, during the startup, I found my program tends to execute `compile_file` function **4 times** :  
```
compile_file(a)
-  compile_file(b)
  - compile_file(c)
- compile_file(c)
```
It called `compile_file(c)` twice with same input value.   
After some experiments I found that in the same revision, new a tracked struct will always return a new struct, rather than trying to find one in the current revision. Changing `compile_file`'s input type from tracked struct to interned struct solve this issue, as the interned struct will always search for the existing data when calling `new`.  
However, there seems to be a memory leak issue with interned structs. After changing tracked struct to interned, every time I change the input the memory usage grows significantly, which is unacceptable.  
Is there a better way to avoid the re-execution of tracked function with same inputs in the same revision?  
Thanks in advance

**Comment by XFFXFF** [comment]
@Chronostasys  If I understand your question correctly, your question can be simplified like this

```rust
#[salsa::tracked(jar = Jar)]
fn final_result(db: &dyn Db, input: MyInput) -> u32 {
    let tracked0 = MyTracked::new(db, input.field(db));
    let tracked1 = MyTracked::new(db, input.field(db));
    intermediate_result(db, tracked0) + intermediate_result(db, tracked1)
}
```

You think that `intermediate_result` will only be called once because `tracked0` and `tracked1` are equal, but in fact, Salsa thinks they are not the same, and if they were, there would be only one `MyTracked::new` here.

> Is there a better way to avoid the re-execution of tracked function with same inputs in the same revision?

I think we can use multiple `input`s, maybe one `input` for one source file in your case (Salsa doesn't have a restriction that says only one `input` can be defined).  The pseudo code might look like the following

```rust
#[salsa::input(jar = Jar)]
struct SourceFile {
    text: String,
}

#[salsa::input(jar = Jar)]
struct SourceFiles {
    files: Vec<SourceFile>,
}

#[salsa::tracked(jar = Jar)]
fn compile_file(db: &dyn Db, source_file: SourceFile) {
    todo!()
}

#[salsa::tracked(jar = Jar)]
fn compile(db: &dyn Db, source_files: SourceFiles) {
    for file in source_files.files(db) {
        compile_file(db, file);
    }
}
```

**Comment by Chronostasys** [comment]
Thanks. Changing SourceFile to input solved my problem.
