### ISSUE TITLE
DebugWithDb shouldn't have generics, put Db as associated type

### ISSUE THREAD

**Issue by xiyuzhai** [salsa-rs/salsa#467]
I went through a lot of troubles these days with DebugWithDb in salsa-2022.

If we use `DebugWithDb<_Db>`, one has to implement too many `DebugWithDb<_Db>` for a single type for different `_Db` in different crate. Even if the code can be written generically, its negative impact on compilation speed is too bad.

Currently, a interned/tracked type in a crate with a db trait `DbTrait` only implements `DebugWithDb<dyn DbTrait>`, which doesn't affect negatively on compilation speed, but makes the type falls back to plain `Debug` when used in other crates.

My suggestion is to reformulate it as
```
pub trait DebugWithDb {
    type Db: ?Sized;
    ....
}
```
In this way, it never falls back to `Debug` in any crate.

**Comment by xiyuzhai** [comment]
I just describe my own experience and ideas. You guys have some deeper considerations.

**Comment by xiyuzhai** [comment]
Currently I've completely remove all Db generics. My whole workspace just have single Db, defined in salsa. Of course, salsa doesn't know Jar types at the time. So the Db stores Jar in a generic way, using Box. And for each crate, `Db` customization is through wrapper. Now there is no single `dyn DbTrait` in use, every db reference is the same type `&Db`.

The net result is strikingly good. The compilation time reduces from 40min (often fails on my computer because of too many compilation units) to 2min. 

So from my own experience, I would suggest against any generic over fundamental things like Db. This will cause later crates to repeat generating code when testing.

**Comment by gavrilikhin-d** [comment]
What's the difference between specifying Db as associated type vs specifying as generic? 

Wouldn't you still need to impl it for every Db you have?

**Comment by xiyuzhai** [comment]
Update: now I recommend using a single Db type for everything. Not associated type. I believe the root of troubles is that salsa is just a library not built into the rust language itself. If only the exact details of a type Db can be determined by all the later crates that use it, the problem would be much simpler. However that's not possible within the current Rust crate system.
