### ISSUE TITLE
Improving Trio-binning assembly using SALSA2

### ISSUE THREAD

**Issue by Larkinhi** [salsa-rs/salsa#471]
Hi, 

I have been working on trio-binning of hybrid genome using PacBio long read sequencing. I YAK paternal and maternal genome and assembled de novo genome ~400 Mb using HIFIASM "pat.mat.asm.fas". Later following BWA (-5SPM) and SAMTOOLS, I mapped HIC to the "pat.mat.asm.fas" assembly. 

Later used BEDTOOLS to convert BAM to BED
bamToBed -i alignment.bam > alignment.bed
sort -k 4 alignment.bed > tmp && mv tmp alignment.bed

SALSA
python2 run_pipeline.py -a pat.mat.asm.fas -l pat.mat.asm.fas.fai -b pat.mat.asm.fas.sorted.bam.bed -e GATC -o scaffold_2 -m yes

Error

Loading SALSA/2.3
  Loading requirement: boost/1.80.0
bedfile loaded
Traceback (most recent call last):
  File "/opt/linux/rocky/8.x/x86_64/pkgs/SALSA/2.3/bin/correct.py", line 66, in <module>
    with open(sys.argv[3],'r') as f:
IOError: [Errno 2] No such file or directory: 'SALSA_output/alignment_iteration_1.bed'

mv: cannot stat 'SALSA_output//asm.cleaned.fasta': No such file or directory
Starting Iteration 1
bedfile started
bedfile loaded
Loading Hi-C links 
Hybrid scaffold graph loaded, nodes = 0 edges = 0
Hi-C implied edges = 0
Starting Iteration 2
bedfile started
bedfile loaded
Starting Iteration 2
Loading Hi-C links 
Hybrid scaffold graph loaded, nodes = 0 edges = 0
Hi-C implied edges = 0
python2 /opt/linux/rocky/8.x/x86_64/pkgs/SALSA/2.3/bin/RE_sites.py -a SALSA_output/assembly.cleaned.fasta -e GATC > SALSA_output/re_counts_iteration_1
python2 /opt/linux/rocky/8.x/x86_64/pkgs/SALSA/2.3/bin/make_links.py -b SALSA_output/alignment_iteration_1.bed -d SALSA_output -i 1 -x abc
python2 /opt/linux/rocky/8.x/x86_64/pkgs/SALSA/2.3/bin/fast_scaled_scores.py -d SALSA_output -i 1

Can anyone help me in this regards? I would appreciate it.

Thank you
LK

**Comment by DropDemBits** [comment]
I think you might want to ask this at <https://github.com/marbl/SALSA> rather than here, since this repository is for the Rust salsa incremental computation library and not the Python SALSA genomics library.

**Comment by Larkinhi** [comment]
Thank you for letting me know. I appreciate it.
