### ISSUE TITLE
Generate builders methods

### ISSUE THREAD

**Issue by gavrilikhin-d** [salsa-rs/salsa#476]
It seems a little inconvenient to pass all fields through `XXX::new` call. 
Can salsa generate builder methods for `interned`, `tracked` and `input` structs?

E.g:
```rs
#[salsa::input]
pub struct SourceProgram {
    #[return_ref]
    pub text: String,
    #[return_ref]
    pub path: PathBuf,
}

SourceProgram::build().with_text("text").with_path("foo.rs").finish()
```

P.S: Names for building functions are just for example, you may pick the ones you like

**Comment by gavrilikhin-d** [comment]
Related to https://github.com/salsa-rs/salsa/issues/385

**Comment by nikomatsakis** [comment]
Agreed! I would like to generate builders. This seems like a good starter issue, @gavrilikhin-d

**Comment by nikomatsakis** [comment]
See also https://github.com/salsa-rs/salsa/pull/418 -- I forget exactly what that PR is doing, maybe same general thing?
