### ISSUE TITLE
Should `InputStorage` return `Default`  for a missing value?

### ISSUE THREAD

**Issue by matklad** [salsa-rs/salsa#49]
Currently, `InputStorage` returns a `Default` value if the key is missing:

https://github.com/salsa-rs/salsa/blob/20c9fbf45c0201e39cfeda4c939160ad1c35132c/src/input.rs#L62

I would think that asking for a missing key is most likely an error, so perhaps we should make this somehow more visible?

**Comment by nikomatsakis** [comment]
Yeah, I debated about this. In practice, I expected most inputs to be defined as `Option` and then for callers to `unwrap`. But perhaps it'd be better to move the unwrap into the "query fn" (and hence to panic for an undefined input); we could then offer some way to query the input like `db.query(MyInput).get(key)` that returns an `Option<T>` if the input is not defined.

**Comment by matklad** [comment]
I think we now panic on missing keys.
