### ISSUE TITLE
Please make a release

### ISSUE THREAD

**Issue by 0-wiz-0** [salsa-rs/salsa#517]
The ruff project is using a [particular commit](https://github.com/astral-sh/ruff/blob/b5ab4ce29361174a5410f868673b46de1809e886/Cargo.toml#L111C65-L111C105) in its `Cargo.toml` file because it needs features that are not in a release yet.
This makes packaging ruff harder than necessary.
Can you please make a new release?

**Comment by MichaReiser** [comment]
Ruff maintainer here. How do you run the ruff build? The salsa code isn't yet used in the ruff CLI. Can you try building ruff with `cargo build --bin ruff`. This should exclude the code depending on salsa.

**Comment by 0-wiz-0** [comment]
Oh. My bad. It is actually not used yet even in the pkgsrc build.

(I had trouble adapting pkgsrc downloads to provide the file for this one and didn't even get to the build step, which caused this bug report. Now I've just excluded salsa from ruff's Cargo.toml and it builds fine.)
