### ISSUE TITLE
re-enable cargo miri

### ISSUE THREAD

**Issue by nikomatsakis** [salsa-rs/salsa#520]
I disabled miri tests in #518 because concurrent-vec is not miri safe and filed https://github.com/orxfun/orx-concurrent-vec/issues/14 to track the underlying issue. We should either figure out why concurrent-vec is not miri-safe and fix it or adopt a new library (e.g., https://github.com/droundy/append-only-vec/ would meet our relatively simple needs if they land https://github.com/droundy/append-only-vec/pull/4; we could fork too).

**Comment by droundy** [comment]
I just released version 0.1.5 of append-only-vec with your PR included.

**Comment by nikomatsakis** [comment]
Thanks!

**Comment by nikomatsakis** [comment]
@droundy have you tested with miri, out of curiosity?

**Comment by davidbarsky** [comment]
Closing this, as miri is re-enabled.
