### ISSUE TITLE
Assign memo ingredients per salsa-struct-ingredient, not globally

### ISSUE THREAD

**Issue by nikomatsakis** [salsa-rs/salsa#600]
Today every tracked function gets assigned a distinct [`MemoIngredientIndex`](https://github.com/salsa-rs/salsa/blob/c6c51a0ea0bb11ce5a449c4b9256c66c5e484fee/src/zalsa.rs#L99-L102). These are used to index into the memo table attached to a salsa struct. But every function can be attached to salsa structs of exactly one kind, so indices only have to be distinct per salsa struct, not globally. This would save a lot of space in larger projects.

**Comment by nikomatsakis** [comment]
# Mentoring instructions

Currently 'memo ingredient indices' are a vector; the values in the vector are the fn ingredient indices that would be storing the memo (this should be documented!).

https://github.com/salsa-rs/salsa/blob/710691d6070cf7cf3638f50ac74f0ac8bce9c48c/src/zalsa.rs#L122-L123

This should be changed into a map of vectors, indexed by the "salsa struct ingredient index" (the ingredient index on which the memo is stored):

```rust
/// Map from the [`IngredientIndex`][] of a salsa struct to a list of
/// [ingredient-indices](`IngredientIndex`)for tracked functions that have this salsa struct as input.
memo_ingredient_indices: RwLock<Map<IngredientIndex, Vec<IngredientIndex>>>
```

then we modify `next_memo_ingredient_index` to take the tracked struct ingredient index as an argument

https://github.com/salsa-rs/salsa/blob/710691d6070cf7cf3638f50ac74f0ac8bce9c48c/src/zalsa.rs#L300-L305

This is called my the various code in salsa-macro-rules, so that will have to be modified to pass in the ingredient index for the salsa struct on which the function is invoked. 

We also modify `ingredient_index_for_memo` similarly

https://github.com/salsa-rs/salsa/blob/710691d6070cf7cf3638f50ac74f0ac8bce9c48c/src/zalsa.rs#L291-L296

and change the one caller of that last method:

https://github.com/salsa-rs/salsa/blob/master/src/tracked_struct.rs#L504

to pass in the `self.ingredient_index`.

**Comment by MichaReiser** [comment]
@ibraheemdev you expressed interest in this task. Let me know if you start working on it so that I can assign it to you.

**Comment by davidbarsky** [comment]
We had some interest/demand from rust-analyzer contributors to contribute to Salsa and @ShoyuVanilla expressed interested in this work. I also believe that he has bandwidth to work on this sooner than @ibraheemdev *and* memory usage is a concern for rust-analyzer, so for those reasons, I'd like to assign him to this issue.
