### ISSUE TITLE
Missing `#[salsa::db]` on impl block should fail compilation

### ISSUE THREAD

**Issue by MichaReiser** [salsa-rs/salsa#613]
The following example misses a `#[salsa::db]` on the `impl Db for Pimpl` but it only fails at runtime with a panic in `as_view`. 

Ideally, we would catch this error at compile time. If this isn't possible, improve the error message to guide users towards the proper fix. 

```rust
use salsa::Accumulator;

#[salsa::db]
trait Db: salsa::Database {}

#[salsa::db]
pub(crate) struct Pimpl {
    storage: salsa::Storage<Self>,
}

#[salsa::db]
impl salsa::Database for Pimpl {
    fn salsa_event(&self, _event: &dyn Fn() -> salsa::Event) {}
}

// #[salsa::db] <-----MISSING
impl Db for Pimpl {
}

#[salsa::input]
struct File {
    #[return_ref]
    contents: String,
}

#[salsa::tracked]
struct Element<'db> {}

#[salsa::accumulator]
struct Diagnostic(&'static str);

#[salsa::tracked]
fn parse_single_file(db: &dyn Db, file: File) -> Option<Element<'_>> {
    Diagnostic("argh").accumulate(db);
    None
}

impl Pimpl {
    pub(crate) fn new() -> Self {
        Self {
            storage: Default::default(),
        }
    }

}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn it_works() {
        let mut pimpl = Pimpl::new();
        let this = &mut pimpl;
        let file = File::new(this, "Hello World!".to_string());
        let node = parse_single_file(this, file);
        // FIXME: This panics with 'Unwrap on None value'
        parse_single_file::accumulated::<Diagnostic>(this, file);
    }
}
```

**Comment by NickNick** [comment]
Without the `#[salsa::db]`, a function `zalsa_db()` is required. Perhaps it would be possible to add another function `fn you_forgot_salsa_db()`?

Coming from someone who hasn't spent a lot of time with macros, but I thought that could be a quick first step towards making this a little more clear.

**Comment by Veykril** [comment]
Is this still accurate? If one forgets the attribute on the impl the `zalsa_db` item is missing and as such things won't compile

**Comment by MichaReiser** [comment]
Yes, this seems fixed. It would be nice if we could customize the error message but Rustcs only supports customizing the error message if a trait implementation is missing.
