### ISSUE TITLE
Garbage collection

### ISSUE THREAD

**Issue by nikomatsakis** [salsa-rs/salsa#7]
As currently implemented, old query results are going to pile up in the hash tables. We need a method that allows users to specify a root set of query results -- that is, queries plus keys. We can then trace all the values reachable from there and evict the rest.

**Comment by matklad** [comment]
It might be useful to GC dependencies of roots as well. For example, when processing a rarely-changed crate, you might want to parse all files, compute available items and symbol indexes, and then throw-away intermediate results (syntax trees) to save memory.

**Comment by nikomatsakis** [comment]
Yes, good point.

**Comment by nikomatsakis** [comment]
So what are the options we need here:

- Some way to specify a set of root queries (probably root queries + keys?)
- Some kind of modes:
    - Keep anything reachable from roots (default)

As for removing intermediate nodes, I can imagine a few options:

    - Drop memoized values from intermediate nodes (reduces ability to do incremental updates, but saves memory)
    - Drop all intermediate nodes (no ability to do incremental updates, but saves more memory)
    - Perhaps some way to specify on a per-query basis whether they get dropped?

**Comment by matklad** [comment]
We can also implement LRU using the existing `verified_at` field.
