### ISSUE TITLE
logging event when gc fires

### ISSUE THREAD

**Issue by nikomatsakis** [salsa-rs/salsa#77]
Pull request https://github.com/salsa-rs/salsa/pull/63 added a `salsa_event` callback that fires at particular times. It would be nice, I imagine, to have an event that fires when a particular descriptor is collected by the garbage collector. This is a *touch* tricky though because we have to create the descriptor and the code doesn't currently have enough information on hand to do that.

**Comment by nikomatsakis** [comment]
## Mentoring tips


Here is where we would need to insert the logging event(s):

https://github.com/salsa-rs/salsa/blob/2d8dbce6c1cc5db335070fc3c8deada49b3b12a4/src/derived.rs#L911-L915

We probably want an event for whenever we return `false`, which indicates that the descriptor is removed; we might want an event for when we clear the `value` too, not sure.

In any case, the challenge there is that even though we know the query `Q` and they key `key`, we can't create a `QueryDescriptor` -- this is because the `QueryDescriptor` type is defined by the database `DB` (because only it knows the full set of descriptors).

How I would fix this is to modify the `sweep` signature:

https://github.com/salsa-rs/salsa/blob/2d8dbce6c1cc5db335070fc3c8deada49b3b12a4/src/derived.rs#L911-L915

In particular, we need to add a parameter with a callback function that — given the key — returned the descriptor. Something like:

```rust
descriptor_fn: fn(&DB, &Q::Key) -> DB::QueryDescriptor
```

The problem now will be supplying the value for that parameter at the two call sites. One of them is easy: `sweep` can be invoked from the `QueryTable` here:

https://github.com/salsa-rs/salsa/blob/2d8dbce6c1cc5db335070fc3c8deada49b3b12a4/src/lib.rs#L220-L225

and the query-table also has a "descriptor fn" field:

https://github.com/salsa-rs/salsa/blob/2d8dbce6c1cc5db335070fc3c8deada49b3b12a4/src/lib.rs#L203

so we can just supply `self.descriptor_fn`.

The other place is a bit trickier; we also call it from the runtime here:

https://github.com/salsa-rs/salsa/blob/2d8dbce6c1cc5db335070fc3c8deada49b3b12a4/src/runtime.rs#L103

we'll have to extend `for_each_query`, I suppose, to also give a `descriptor_fn` parameter. `for_each_query` is defined in the `database_storage!` macro:

https://github.com/salsa-rs/salsa/blob/2d8dbce6c1cc5db335070fc3c8deada49b3b12a4/src/lib.rs#L613-L626

But what value should `for_each_query` supply? The `descriptor_fn` that tables get is defined here:

https://github.com/salsa-rs/salsa/blob/2d8dbce6c1cc5db335070fc3c8deada49b3b12a4/src/lib.rs#L667-L672

So, to bring it all together, we need to do the following:

- Somehow give the `sweep` function the ability to create descriptors, probably by adding a `descriptor_fn` parameter (this will require modifying [the `QueryStorageMassOps` trait](https://github.com/salsa-rs/salsa/blob/2d8dbce6c1cc5db335070fc3c8deada49b3b12a4/src/plumbing.rs#L40-L46), which defines `sweep`, along with its two impls)
- Extend `for_each_query` so include the descriptor fn as one of the arguments it gives
- Tweak the macro to create the query descriptor in the same way

(I had contemplated maybe refactoring `for_each` so that instead of giving two parameters, it gives a struct that pairs them up, something analogous to the existing `QueryStorageTable`, like `QueryStorageMassTable`. The main difference from `QueryStorageTable` is that `QueryStorageTable` combines the query, database, descriptor function, *and the key* -- but the "mass table" would not need the key. Seems nicer but not particularly **necessary**.)

**Comment by nikomatsakis** [comment]
I created [a Zulip topic] for discussing this issue.

[a Zulip topic]: https://salsa.zulipchat.com/#narrow/stream/146365-good-first-issue/topic/.2377.20logging.20event.20when.20GC.20fires

**Comment by mheiber** [comment]
Given that GC was removed in https://salsa-rs.github.io/salsa/rfcs/RFC0008-Remove-Garbage-Collection.html, is this issue stale?

**Comment by nikomatsakis** [comment]
No longer relevant, there is no GC.
