### ISSUE TITLE
support parallel execution within queries

### ISSUE THREAD

**Issue by nikomatsakis** [salsa-rs/salsa#80]
Right now, if a query were to invoke `fork` on its database and then perform other queries, those dependencies would not be tracked. Seems bad!

UPDATE: We rule out using `fork` within queries, but we still need some way to invoke queries in parallel. I imagined something like `db.query(Foo).for_all(keys)`, which would execute `keys` across a thread-pool, but we have to think about it.

**Comment by matklad** [comment]
Note that https://github.com/salsa-rs/salsa/pull/78 sort-of fixes it, but forbidding forking during query execution.

**Comment by nikomatsakis** [comment]
Yes, and it may be that the answer is to only permit queries to do "higher-level" parallel operations, like `db.query(Q).for_all(Ks)` or something.

**Comment by nikomatsakis** [comment]
(Which can *internally* use some sort of mechanism that involves a fork, but that would be hidden.)

**Comment by matklad** [comment]
FWIW, I think I have a use-case in Rust analyzer, where I can use internal parallelism. Specifically, a first-phase of per-crate import resolution needs to collect items for all modules, and that could be done in parallel.

>I imagined something like db.query(Foo).for_all(keys), which would execute keys across a thread-pool, but we have to think about it.

I've though about it today, and a possible alternative would be some kind of scoped-concurrency approach, where we let the user drive the parallel computation:

```
db.par(|db| {
// db is `Clone + Send` and parametrized over lifetime (to forbid escaping from the closure).
// db is a fresh execution context (the dep stack is empty)
// at the end of the scope, we record all top-level queries done via `db` as *parallel* dependnecies
})
```

The problem with this approach is that we can push only half of the parallelization work onto the user: when *verifying* queries, we will either use a sequential algo, or will have to do our own parallelization (hence, we need to remember which deps are "parallel").

**Comment by NotAFile** [comment]
Is this issue still up to date or have there been any changes?

**Comment by nikomatsakis** [comment]
I'm still in this idea, but I'm going to close this issue for now.
