### ISSUE TITLE
private query group dependencies

### ISSUE THREAD

**Issue by nikomatsakis** [salsa-rs/salsa#86]
Right now, query groups depend on one another by declaring supertraits. My original plan was to support "private queries" by making two groups: a private query group `Priv`, and a public query group `Pub: Priv`. The idea was that most code would only import that `Pub` trait and would thus be prevented (by convention) from using private queries. However, this doesn't work, because Rust automatically makes supertrait methods invokable, so if you import `Pub`, you get `Priv`.

@matklad suggested permitting declaring "private dependencies" in the query group. This would look something like this (bikeshed welcome):

```rust
salsa::query_group!
    trait Pub {
        where Self: Priv;

        fn some_pub_query() -> u32 { ... }
    }
}
```

Note that the `where Priv` is *inside* the `trait`. (@matklad's original proposal was `use trait Priv;`.)

The effect of this would be to move the "where clause" from the trait declaration (where it is public) to the *impl*. So instead of making

```rust
trait Pub: Priv { .. }
impl<DB: Pub> QueryFunction<DB> for SomePubQuery { .. }
```

we would move the `Priv` dependency onto the impl, sort of like this

```rust
trait Pub { .. }
impl<DB: Pub> QueryFunction<DB> for SomePubQuery 
where 
    Self: Priv,
{ .. }
```

I think this would work, anyway...

**Comment by matklad** [comment]
SGTM!

Although, having trait inheritance sometimes is useful as well, if you want to avoid repeating trait sums all over the place, so perhaps we should do both.

**Comment by nikomatsakis** [comment]
Closing in favor of https://github.com/salsa-rs/salsa-rfcs/pull/3
